# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='This is a subtitle', max_length=200),
        ),
    ]
